format = """
$username\
$hostname\
$kubernetes\
$aws\
$line_break\
$directory\
$shlvl\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$env_var\
$line_break\
$character"""

# $package\
# $openstack\
# 
# $crystal\
# $custom\
# $cmd_duration\
# $line_break\
# $lua\
# $jobs\
# $battery\
# $time\
# $status\

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the newline at the start of the prompt
# add_newline = false

[hostname]
ssh_only = false
format="[@$hostname]($style) "


[directory]
truncation_length = 3
truncate_to_repo = true 
format = " [$path]($style)[$read_only]($read_only_style) "
# 🏠    

[character]
success_symbol = "[](bold green)"
# ❯    ✗     
error_symbol = "[](bold red)"
vicmd_symbol = "[V](bold green) "

[git_branch]
symbol = " "
# symbol = ""
# symbol = "🌱        "
format="[$symbol$branch]($style)"
style = "fg:103"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
staged = '[++\($count\)](green)'
format = '([\[$all_status$ahead_behind\]]($style) )'

[kubernetes]
symbol = "謁"
# ⛵   
format='[$symbol$context(\($namespace\))]($style) '
style = "fg:105"
disabled = false

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[python]
symbol = "🐍"
#🐍 🦖 🐉
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
style = "bright-yellow"

[aws]
symbol = " "
# symbol = "  "
format = '[$symbol($profile|)($region)]($style)'
style = "yellow"

[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "us-e1"
us-west-1 = "us-w1"
us-east-2 = "us-e2"
us-west-2 = "us-w2"
eu-east-1 = "eu-e1"
eu-east-2 = "eu-e2"
eu-west-1 = "eu-w1"
eu-west-2 = "eu-w2"
eu-north-1 = "eu-n1"
eu-north-2 = "eu-n2"
eu-central-1 = "eu-c1"
eu-central-2 = "eu-c2"
eu-central-3 = "eu-c3"

[golang]
symbol = " "
#   
format = "[$symbol($version )]($style)"

[ruby]
symbol = " "
# 💎      
format = "[$symbol($version)]($style) "
style = "red"

[perl]
format = "[$symbol($version)]($style) "

[terraform]
format = "[$symbol$workspace]($style) "
symbol = "💠"

[env_var.OP_AWS]
symbol = ""
format = "[$env_value]($style)"
style = "bold dimmed green"
variable = "OP_AWS"
default = ""

[nodejs]
format="[$symbol($version )]($style)"
